apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: servicio-streamlit-datapath-nombre-apellido
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/project-mlops9-ino-streamlit/repo-mlops11-streamlit-datapath/image-v1-streamlit-datapath:latest
          env:
          ports:
            - containerPort: 4000